;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/AbilitySystem/GameplayTags/DT_Messages.DT_Messages
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Cooldown.Knight.HandOfMerlin",NewTagName="Cooldown.Knight.MagicHand")
+GameplayTagRedirects=(OldTagName="Abilities.Knight.HandOfMerlin",NewTagName="Abilities.Knight.MagicHand")
+GameplayTagList=(Tag="Abilities.Barbarian.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Barbarian.Secondary",DevComment="")
+GameplayTagList=(Tag="Abilities.Barbarian.Thunderstrike",DevComment="")
+GameplayTagList=(Tag="Abilities.Egyptian.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Egyptian.Secondary",DevComment="")
+GameplayTagList=(Tag="Abilities.Enemy.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Enemy.Attack.Summon",DevComment="")
+GameplayTagList=(Tag="Abilities.Futureman.ChargeShot",DevComment="")
+GameplayTagList=(Tag="Abilities.Futureman.ChronoShift",DevComment="")
+GameplayTagList=(Tag="Abilities.Futureman.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Highlander.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Hippie.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Hippie.PsychedelicVision",DevComment="")
+GameplayTagList=(Tag="Abilities.Knight.MagicHand",DevComment="")
+GameplayTagList=(Tag="Abilities.Knight.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Native.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Abilities.Other.Aim",DevComment="")
+GameplayTagList=(Tag="Abilities.Other.Block",DevComment="")
+GameplayTagList=(Tag="Abilities.Other.Dodge",DevComment="")
+GameplayTagList=(Tag="Abilities.Roman.Primary",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.Effect.Stagger",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.RightHand.Arrow",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.Weapon.Blaster.Left.Tip",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.Weapon.Blaster.Right.Tip",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.Weapon.Dagger.Left",DevComment="")
+GameplayTagList=(Tag="Combat.Socket.Weapon.Dagger.Right",DevComment="")
+GameplayTagList=(Tag="Cooldown.Barbarian.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Barbarian.Secondary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Barbarian.Thunderstrike",DevComment="")
+GameplayTagList=(Tag="Cooldown.Common.Block",DevComment="")
+GameplayTagList=(Tag="Cooldown.Common.Dodge",DevComment="")
+GameplayTagList=(Tag="Cooldown.Common.Interaction",DevComment="")
+GameplayTagList=(Tag="Cooldown.Common.LockOn",DevComment="")
+GameplayTagList=(Tag="Cooldown.Egyptian.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Egyptian.Secondary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Enemy.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Futureman.Attack.ChargeShot",DevComment="")
+GameplayTagList=(Tag="Cooldown.Futureman.Attack.ChronoShift",DevComment="")
+GameplayTagList=(Tag="Cooldown.Futureman.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Highlander.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Hippie.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Hippie.PsychedelicVision",DevComment="")
+GameplayTagList=(Tag="Cooldown.Knight.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Knight.MagicHand",DevComment="")
+GameplayTagList=(Tag="Cooldown.Native.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Cooldown.Roman.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Effect.Recovery.Health",DevComment="")
+GameplayTagList=(Tag="Effect.Recovery.Mana",DevComment="")
+GameplayTagList=(Tag="Effect.State.AnkhOfVitalis",DevComment="")
+GameplayTagList=(Tag="Effect.State.ChronoShift",DevComment="")
+GameplayTagList=(Tag="Effect.State.HandOfMerlin",DevComment="")
+GameplayTagList=(Tag="Effect.State.Moving",DevComment="")
+GameplayTagList=(Tag="Event.Montage.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Barbarian.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Barbarian.Secondary.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Barbarian.Secondary.Hold",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Barbarian.Thunderstrike",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Combo.NextAvailable",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Common.Dust",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Common.Parry.Land",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Egyptian.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Egyptian.Secondary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Egyptian.Secondary.EffectBegin",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Egyptian.Secondary.EffectEnd",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Egyptian.Secondary.Heal",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Enemy.Attack.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Equip",DevComment="")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Futureman.ChargeShot.Hit",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Futureman.ChargeShot.Ready",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Futureman.ChronoShift.Activate",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Futureman.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Highlander.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Highlander.Flip",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Hippie.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Hippie.PsychedelicVision",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Knight.MagicHand",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Knight.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Native.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Roman.Primary",DevComment="")
+GameplayTagList=(Tag="Event.Montage.Target.FaceTarget",DevComment="")
+GameplayTagList=(Tag="Fish.Rarity.Common",DevComment="")
+GameplayTagList=(Tag="Fish.Rarity.Rare",DevComment="")
+GameplayTagList=(Tag="Fish.Rarity.Special",DevComment="")
+GameplayTagList=(Tag="Fish.Tag.Day",DevComment="")
+GameplayTagList=(Tag="Fish.Tag.Night",DevComment="")
+GameplayTagList=(Tag="Fish.Tag.Rain",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ArcaneShards",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Barbarian.Shockwave",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Barbarian.Thunderstrike",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Egyptian.Primary",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Fishing.ClearEffect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Fishing.Daylight",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Fishing.Nighttime",DevComment="")
+GameplayTagList=(Tag="GameplayCue.MeleeImpact",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockBurst",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShockLoop",DevComment="")
+GameplayTagList=(Tag="InputTag.Aim",DevComment="")
+GameplayTagList=(Tag="InputTag.Dialog.Bottom",DevComment="")
+GameplayTagList=(Tag="InputTag.Dialog.Left",DevComment="")
+GameplayTagList=(Tag="InputTag.Dialog.Right",DevComment="")
+GameplayTagList=(Tag="InputTag.Dialog.Top",DevComment="")
+GameplayTagList=(Tag="Item.Type.Consumable.Crystal.Health",DevComment="")
+GameplayTagList=(Tag="Item.Type.Consumable.Crystal.Mana",DevComment="")
+GameplayTagList=(Tag="Item.Type.Consumable.Potion.Health",DevComment="")
+GameplayTagList=(Tag="Item.Type.Consumable.Potion.Mana",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Barbarian.Axe",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Egyptian.Staff",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Futureman.Blaster",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Highlander.Dagger",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Knight.Sword",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Native.Bow",DevComment="")
+GameplayTagList=(Tag="Item.Type.Equipment.Weapon.Roman.Spear",DevComment="")
+GameplayTagList=(Tag="Item.Type.Fish.FiletOFish",DevComment="")
+GameplayTagList=(Tag="Item.Type.Fish.FreshwaterCod",DevComment="")
+GameplayTagList=(Tag="Item.Type.Fish.Goldfish",DevComment="")
+GameplayTagList=(Tag="Item.Type.Fish.LargeMouthBass",DevComment="")
+GameplayTagList=(Tag="Item.Type.Key.DecisionTree.01",DevComment="")
+GameplayTagList=(Tag="Item.Type.Key.Demo.Floor01",DevComment="Key to unlock level 1 gate")
+GameplayTagList=(Tag="Item.Type.Key.Demo.Floor02",DevComment="")
+GameplayTagList=(Tag="Item.Type.Key.Demo.Floor04",DevComment="")
+GameplayTagList=(Tag="Message.Item.Fish",DevComment="")
+GameplayTagList=(Tag="Message.Key.Level1",DevComment="Message for picking up level 1 key")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Barbarian.Axe",DevComment="")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Egyptian.Staff",DevComment="")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Highlander.Dagger",DevComment="")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Knight.Sword",DevComment="")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Native.Bow",DevComment="")
+GameplayTagList=(Tag="Player.Equipped.Weapon.Roman.Spear",DevComment="")
+GameplayTagList=(Tag="Significance.Category.Enemy",DevComment="")

